#pragma once

#include "resource.h"
#include  "stdafx.h"
#include "model\Shape.h"
#include "model\Rectangle.h"
#include "model\Triangle.h"
#include "model\Circle.h"
#include "model\ShapeFactory.h"
#include "model\Delete.h"
#include "model\Draw.h"
#include "model\Resize.h"
#include "model\Move.h"
#include "model\FillColor.h"
#include "model\CommandFactory.h"
#include "model\file.h"
#include "FilePainter.h"
#include "shape_select.h"